"""Built-in prototype training utterances for the lightweight intent classifier.

This is a demo corpus, not a published dataset. It is intentionally diverse so
benign mentions of sensitive words do not dominate classification.
"""

INTENT_TRAINING = [
    # --- normal_conversation ---
    ("normal_conversation", "Hey, how are you doing today?"),
    ("normal_conversation", "Hey, are we still meeting at five?"),
    ("normal_conversation", "Are we still on for five o'clock?"),
    ("normal_conversation", "Can we meet at 5?"),
    ("normal_conversation", "Let's discuss the project tomorrow."),
    ("normal_conversation", "Can we schedule a meeting for three pm?"),
    ("normal_conversation", "I wanted to check how the team is doing."),
    ("normal_conversation", "Are you free for lunch this weekend?"),
    ("normal_conversation", "Thanks for sending the presentation yesterday."),
    ("normal_conversation", "The weather has been really bad this week."),
    ("normal_conversation", "I will call you back after the standup."),
    ("normal_conversation", "Did you reach home safely?"),
    ("normal_conversation", "Let me know what time works for you."),
    ("normal_conversation", "How was your trip?"),
    ("normal_conversation", "I'll call you tomorrow."),
    ("normal_conversation", "Did you finish the assignment?"),
    ("normal_conversation", "Can you send me yesterday's report?"),
    ("normal_conversation", "Please send the attendance report when you can."),
    ("normal_conversation", "Could you share today's attendance report?"),
    ("normal_conversation", "Hey it's me, just checking in."),
    ("normal_conversation", "Hope your day is going well."),
    ("normal_conversation", "Sorry I missed your call earlier."),
    ("normal_conversation", "Catch you after the meeting."),
    ("normal_conversation", "The client liked the slides."),
    ("normal_conversation", "We can talk about this later."),
    ("normal_conversation", "Did you get my earlier message?"),
    ("normal_conversation", "I'm running five minutes late."),
    ("normal_conversation", "See you at the office."),
    ("normal_conversation", "That sounds good to me."),
    ("normal_conversation", "I received an OTP."),
    ("normal_conversation", "Did you receive the OTP?"),
    ("normal_conversation", "The OTP came through on my phone."),
    ("normal_conversation", "Someone asked me for my OTP yesterday."),
    ("normal_conversation", "I already submitted the report."),
    ("normal_conversation", "Please send the minutes of the meeting."),
    ("normal_conversation", "Can you forward yesterday's notes?"),
    ("normal_conversation", "Kya hum paanch baje mil rahe hain?"),
    ("normal_conversation", "Kal milte hain office mein."),
    ("normal_conversation", "How was the conference call?"),
    ("normal_conversation", "Nothing urgent, just a quick hello."),
    ("normal_conversation", "Can you explain the project timeline?"),
    ("normal_conversation", "I will share the report after lunch."),
    ("normal_conversation", "Please remind me about the five pm meeting."),
    ("normal_conversation", "We should wrap up the agenda first."),
    ("normal_conversation", "Thanks, that helps a lot."),
    ("normal_conversation", "Are you joining the standup?"),
    ("normal_conversation", "I finished the assignment last night."),
    ("normal_conversation", "Let's push the call to tomorrow morning."),
    ("normal_conversation", "Send me the slide deck from yesterday if you have it."),
    ("normal_conversation", "No need to transfer anything, just the notes."),

    # --- security_support / advice / discussion of scams ---
    ("security_support", "The bank will never ask for your OTP."),
    ("security_support", "The bank will never ask you for your OTP."),
    ("security_support", "Never share your password with anyone."),
    ("security_support", "Do not share your OTP with anyone."),
    ("security_support", "Don't give your PIN to callers."),
    ("security_support", "Someone tried to scam me yesterday."),
    ("security_support", "Someone tried to steal my OTP."),
    ("security_support", "Can you explain why OTPs are dangerous?"),
    ("security_support", "Banks do not call and ask for passwords."),
    ("security_support", "Please visit the official branch to complete verification."),
    ("security_support", "I want to report suspicious activity."),
    ("security_support", "I think that call was a phishing attempt."),
    ("security_support", "You should never read an OTP to a stranger."),
    ("security_support", "Legitimate support will never ask for CVV."),
    ("security_support", "If anyone asks for OTP, hang up and call the official number."),
    ("security_support", "This is a reminder not to share credentials."),
    ("security_support", "We do not need your password to help you."),
    ("security_support", "Please change your password if you shared it by mistake."),
    ("security_support", "I blocked the number after they asked for OTP."),
    ("security_support", "Let's review how to spot social engineering."),
    ("security_support", "OTP ko kabhi share mat karna."),
    ("security_support", "Bank kabhi OTP nahi maangta."),
    ("security_support", "Never send your UPI PIN even if they sound urgent."),
    ("security_support", "A real agent will not ask you to stay on the line for OTP."),
    ("security_support", "I received a fake security alert yesterday."),
    ("security_support", "Please ignore messages asking for verification codes."),
    ("security_support", "Our fraud awareness page explains why OTPs are sensitive."),
    ("security_support", "You should independently verify before sharing account details."),
    ("security_support", "I am reporting that somebody tried to steal my password."),
    ("security_support", "Do not confirm CVV on a phone call."),

    # --- account_information ---
    ("account_information", "Can you tell me my account balance?"),
    ("account_information", "I want information about my account."),
    ("account_information", "Please explain the status of my account."),
    ("account_information", "Can you help me with my account details?"),
    ("account_information", "What is the last transaction on my statement?"),
    ("account_information", "I need to know when my card was issued."),
    ("account_information", "Could you check whether my payment was received?"),
    ("account_information", "Is my account still active?"),
    ("account_information", "Can you confirm if the salary has been credited?"),
    ("account_information", "What is the available limit on my card?"),
    ("account_information", "I want to know my IFSC for this account."),
    ("account_information", "Please tell me the status of yesterday's NEFT."),
    ("account_information", "Has the cheque been cleared?"),
    ("account_information", "I need a copy of my account statement."),
    ("account_information", "Can you check why my UPI failed?"),
    ("account_information", "Mera account balance kya hai?"),
    ("account_information", "When does this FD mature?"),
    ("account_information", "Show me the last three transactions."),
    ("account_information", "I want to understand the charges on my account."),
    ("account_information", "Was there any debit after 5 pm?"),

    # --- authorization_request ---
    ("authorization_request", "Please approve this access request."),
    ("authorization_request", "Can you authorize access to this document?"),
    ("authorization_request", "Please confirm that I can access the system."),
    ("authorization_request", "Approve my request to access the file."),
    ("authorization_request", "Grant me admin rights on the shared drive."),
    ("authorization_request", "Sign off on the change request before the deadline."),
    ("authorization_request", "Add my address to the approved sender list."),
    ("authorization_request", "Reset the multi factor authentication for my login."),
    ("authorization_request", "Can you whitelist my device?"),
    ("authorization_request", "Please elevate my permissions for today."),
    ("authorization_request", "I need temporary access to the payroll folder."),
    ("authorization_request", "Approve VPN access for the contractor."),
    ("authorization_request", "Can you unlock my account from your side?"),
    ("authorization_request", "Please add me as an authorised signatory."),
    ("authorization_request", "Allow me to download the restricted report."),
    ("authorization_request", "I need you to authorise this pull request."),
    ("authorization_request", "Can you share the access token for the staging app?"),
    ("authorization_request", "Please enable my login on the production console."),

    # --- personal_information_request ---
    ("personal_information_request", "Tell me your Aadhaar number."),
    ("personal_information_request", "Give me your date of birth and address."),
    ("personal_information_request", "I need your personal identification details."),
    ("personal_information_request", "Send me your private information."),
    ("personal_information_request", "What is your PAN card number?"),
    ("personal_information_request", "Confirm your mother's maiden name."),
    ("personal_information_request", "Give me the last four digits of your card."),
    ("personal_information_request", "Tell me your registered mobile number and email."),
    ("personal_information_request", "Confirm your account number."),
    ("personal_information_request", "Can you confirm your account number?"),
    ("personal_information_request", "Please read your full address."),
    ("personal_information_request", "What is your date of birth?"),
    ("personal_information_request", "Share your phone number for verification."),
    ("personal_information_request", "I need your employee ID and home address."),
    ("personal_information_request", "Tell me your full name as on the PAN."),
    ("personal_information_request", "Confirm the last four of your Aadhaar."),
    ("personal_information_request", "Please give me your registered email id."),
    ("personal_information_request", "Apna account number batao."),
    ("personal_information_request", "Verify your identity by telling me your DOB."),
    ("personal_information_request", "I need you to confirm your KYC phone number."),

    # --- sensitive_data_request ---
    ("sensitive_data_request", "Send me the confidential employee database."),
    ("sensitive_data_request", "Give me the private customer records."),
    ("sensitive_data_request", "I need the company's confidential files."),
    ("sensitive_data_request", "Send the employee data to my email."),
    ("sensitive_data_request", "Share the salary sheet for the whole team."),
    ("sensitive_data_request", "Export the client contact list and send it over."),
    ("sensitive_data_request", "I want the internal audit report right now."),
    ("sensitive_data_request", "Attach the customer KYC documents."),
    ("sensitive_data_request", "I need the complete employee database."),
    ("sensitive_data_request", "Send the employee database to my personal Gmail."),
    ("sensitive_data_request", "Send the entire employee database to my personal Gmail."),
    ("sensitive_data_request", "Mail the HR database to my personal email."),
    ("sensitive_data_request", "Please dump the customer database and send it."),
    ("sensitive_data_request", "I need all employee PAN and Aadhaar copies."),
    ("sensitive_data_request", "Forward the payroll master to me."),
    ("sensitive_data_request", "Export user credentials from the admin panel."),
    ("sensitive_data_request", "Send the employee database."),
    ("sensitive_data_request", "Share the entire client KYC folder."),
    ("sensitive_data_request", "I want the source code and customer list."),
    ("sensitive_data_request", "Send me yesterday's report" ),  # borderline; extra examples of truly sensitive
    ("sensitive_data_request", "Give me access to the employee database dump."),
    ("sensitive_data_request", "Send the employee database to rahul@gmail.com."),

    # --- financial_request ---
    ("financial_request", "Transfer fifty thousand rupees to this account."),
    ("financial_request", "Transfer ₹50,000 to this new account."),
    ("financial_request", "Transfer ₹50,000 to account 1234567890."),
    ("financial_request", "Please make the payment immediately."),
    ("financial_request", "Send the money to this bank account."),
    ("financial_request", "Approve this financial transaction now."),
    ("financial_request", "Pay the fine to this account before evening."),
    ("financial_request", "Do a UPI transfer to the number I am sending."),
    ("financial_request", "Release the vendor payment today itself."),
    ("financial_request", "Wire the amount to the new account details."),
    ("financial_request", "Buy gift cards and send me the codes."),
    ("financial_request", "Deposit the security amount into this wallet."),
    ("financial_request", "Please transfer the funds to my personal account."),
    ("financial_request", "Send 50000 to this UPI id."),
    ("financial_request", "Move the money to a different account."),
    ("financial_request", "Pay this invoice to the new vendor account."),
    ("financial_request", "I need you to do a NEFT of two lakh."),
    ("financial_request", "UPI kar do is number pe abhi."),
    ("financial_request", "Transfer the salary to this alternate account."),
    ("financial_request", "Send rupees fifty thousand immediately."),
    ("financial_request", "Please process a payment of 50000 rupees."),
    ("financial_request", "Refund the amount to this wallet address."),

    # --- credential_request ---
    ("credential_request", "Tell me the OTP you just received."),
    ("credential_request", "Please give me your one time password."),
    ("credential_request", "Please send me the OTP you just received."),
    ("credential_request", "Give me the OTP you just received."),
    ("credential_request", "Send the OTP."),
    ("credential_request", "Share the OTP."),
    ("credential_request", "Read out the OTP."),
    ("credential_request", "Send me your PIN and password."),
    ("credential_request", "I need the verification code from your phone."),
    ("credential_request", "Read out the six digit code in your message."),
    ("credential_request", "Share the CVV printed on the back of the card."),
    ("credential_request", "What is your net banking login password?"),
    ("credential_request", "Forward the SMS code to me right now."),
    ("credential_request", "Just tell me the code, I will handle the rest."),
    ("credential_request", "Give me the OTP so I can cancel the transaction."),
    ("credential_request", "I need your UPI PIN to reverse the payment."),
    ("credential_request", "Tell me the security code and do not delete the message."),
    ("credential_request", "Tell me your password."),
    ("credential_request", "Please share the OTP."),
    ("credential_request", "Confirm the OTP by reading it to me."),
    ("credential_request", "Type the OTP here."),
    ("credential_request", "What is the OTP on your phone?"),
    ("credential_request", "Give me your ATM pin."),
    ("credential_request", "Send me the password for the mail account."),
    ("credential_request", "OTP batao jo abhi aaya hai."),
    ("credential_request", "Password bata do jaldi."),
    ("credential_request", "Read me the verification code you received."),
    ("credential_request", "Forward that one time password to this number."),
    ("credential_request", "I need you to share the OTP immediately."),
    ("credential_request", "Tell me the passcode from the SMS."),
]

# Fix the accidental mixed example
INTENT_TRAINING = [x for x in INTENT_TRAINING if x[1] != "Send me yesterday's report"]
INTENT_TRAINING.append(("normal_conversation", "Send me yesterday's report."))
INTENT_TRAINING.extend([
    ("normal_conversation", "How are you?"),
    ("normal_conversation", "I received my salary today."),
    ("normal_conversation", "The payment was successful."),
    ("normal_conversation", "I sent ₹500 to Rahul."),
    ("normal_conversation", "I forgot my password."),
    ("normal_conversation", "I am going to reset my password."),
    ("normal_conversation", "Please send the report when you have time."),
    ("account_information", "I need to check my bank balance."),
    ("account_information", "What is my account balance?"),
    ("account_information", "Can you explain NEFT?"),
    ("account_information", "When will my salary arrive?"),
    ("account_information", "I made a UPI payment."),
    ("account_information", "My bank account is frozen."),
    ("account_information", "I need to update my bank details."),
    ("security_support", "The bank told me never to share my OTP."),
    ("security_support", "Never share your OTP."),
    ("security_support", "The bank will never ask for your PIN."),
    ("security_support", "Don't give anyone your password."),
    ("security_support", "Remember, never transfer money to an unknown account."),
    ("security_support", "I will NOT share my OTP."),
    ("security_support", "I am not asking for your password."),
    ("security_support", "Don't send money to this account."),
    ("security_support", "He threatened me for my password."),
    ("security_support", "The scammer asked for my bank details."),
    ("security_support", "I already gave the payment yesterday."),
    ("credential_request", "Tell me your OTP."),
    ("credential_request", "Send me your UPI PIN."),
    ("credential_request", "Give me your password."),
])
